### ISSUE TITLE
Duel end doesn't apply grovel debuff

### ISSUE THREAD

**Issue by Daribon** [Crestfall/JadefireTracker#12]
Grovel doesn't seem to work (the debuff that is applied after you lose a duel). On Crestfall, when you "cast" grovel you won't perform any emote and no debuff will be applied on the character.

So I went to a mangos server and casted grovel and noticed that a debuff was applied on character and that the emote was performed.

I guess it has something to do with the debuff not being applied correctly.

**Comment by AsuraDev** [comment]
Cause is known, but requires changes. There's a few issues with duels overall.

**Comment by AsuraDev** [comment]
Fixed, as well as the DoTs and damage after duel end.
