### ISSUE TITLE
[NPC] Multiple Vultros spawn

### ISSUE THREAD

**Issue by rzeg** [Crestfall/JadefireTracker#127]
There are currently multiples of Vultros spawned in Westfall.

Seems like every spawnpoint he can spawn has been spawned.
![d](http://puu.sh/imlhi/0c761377b0.jpg)

**Comment by AsuraDev** [comment]
Closing this as it is not currently a "bug". We're working on a rare spawn pooling system, so all of the their spawns are currently active.
