### ISSUE TITLE
[NPC] Keldas - Gossip text missing. (Teldrassil)

### ISSUE THREAD

**Issue by mirome** [Crestfall/JadefireTracker#14]
Keldas - Pet Trainer (npc=3306)

![keldas](https://cloud.githubusercontent.com/assets/6696700/8026376/c407a238-0d6a-11e5-95ed-5635caff035d.jpg)

Tested on Night Elf Druid.

**Comment by Daribon** [comment]
Still missing gossip text, was this ever applied to db?
