### ISSUE TITLE
Lightning shield no cooldown

### ISSUE THREAD

**Issue by Daribon** [Crestfall/JadefireTracker#148]
Lightning shield can currently use all charges within a second. It shouldn't be possible since the shield should only be able to proc once every few seconds.

Tooltip says: "Only one ball will fire every few seconds".

I'm not sure of the cooldown between the charges so it needs to be researched.

From what I've read on Wowhead and on WoWiki, there was patch note in 4.2.0 where it said
"Water Shield has had its internal cooldown reduced to 3.5 seconds, once again matching other shields."  and the comments I've read on wowhead have been talking about lightning shield having about 3 to 4 seconds internal cd. My guess is that in vanilla, the cd was 3,5 seconds too.

Source: http://wowwiki.wikia.com/Water_Shield, http://www.wowhead.com/spell=324/lightning-shield#comments

**Comment by AsuraDev** [comment]
Fixed.
