### ISSUE TITLE
[Profession] Skill levels posted in chat.

### ISSUE THREAD

**Issue by mirome** [Crestfall/JadefireTracker#16]
When learning a new profession, certain skill levels are posted in chat.

![First Aid](https://cloud.githubusercontent.com/assets/6696700/8026416/51b1068c-0d6c-11e5-9af1-024af2a6f664.jpg)

**Comment by Daribon** [comment]
Can confirm, known bug from before.

**Comment by AsuraDev** [comment]
Confirmed. Cause found.

**Comment by AsuraDev** [comment]
Fixed. Will be applied with update tomorrow.
