### ISSUE TITLE
[Quest] Recipe of the Kaldorei (Teldrassil)

### ISSUE THREAD

**Issue by mirome** [Crestfall/JadefireTracker#17]
Recipe of the Kaldorei (quest=4161)

Recieved item: [Axe of the Deep Woods] posted in chat although no item was received.

![recipe of the kaldorei](https://cloud.githubusercontent.com/assets/6696700/8026532/0a946996-0d72-11e5-9480-0757ca4c62d1.jpg)

**Comment by AsuraDev** [comment]
Fixed. Update is on test server.

**Comment by mirome** [comment]
Fix confirmed.

**Comment by AsuraDev** [comment]
Confirmed, as weird as this is. I just turned it in my local server and this appeared.

**Comment by AsuraDev** [comment]
Okay, I'm just bad. Bad structure in SMSG_QUESTGIVER_QUEST_COMPLETE. Will be fixed in tomorrows update.

http://i.imgur.com/DsJx9bQ.png
