### ISSUE TITLE
[Profession] Skinning spell can be cast on any slain mob.

### ISSUE THREAD

**Issue by mirome** [Crestfall/JadefireTracker#19]
It appears that any slain mob can be skinned, although no loot drops, your skinning skill does increase.

![skinning](https://cloud.githubusercontent.com/assets/6696700/8026697/7dcafa9a-0d79-11e5-8c3f-84e7117e6fa6.jpg)

**Comment by AsuraDev** [comment]
Fixed. Also added a few extra fixes like checking skill on cast instead of at end of cast. Will be on Alpha realm tomorrow.
