### ISSUE TITLE
Greetings! gossip incorrect

### ISSUE THREAD

**Issue by Daribon** [Crestfall/JadefireTracker#191]
There seems to be an awful lot of NPCs that have the Greetings! gossip text and I'm starting to wonder if they ain't supposed to have other gossip texts.

![greetingssss](https://cloud.githubusercontent.com/assets/6137576/8413351/2bbbbd66-1e90-11e5-91f4-d7c11630815b.PNG)
![dargreets](https://cloud.githubusercontent.com/assets/6137576/8413353/2bbd550e-1e90-11e5-9b1e-105d633a1d99.PNG)
![greenhold](https://cloud.githubusercontent.com/assets/6137576/8413352/2bbc41dc-1e90-11e5-8231-b1ed99b6d6ad.PNG)
![greens](https://cloud.githubusercontent.com/assets/6137576/8413355/2bc012c6-1e90-11e5-894a-89d39b51d506.PNG)
![gritens](https://cloud.githubusercontent.com/assets/6137576/8413354/2bbeca10-1e90-11e5-87b0-465ea3e5db9d.PNG)
![greets](https://cloud.githubusercontent.com/assets/6137576/8413356/2bc23038-1e90-11e5-8479-55317749e77f.PNG)
![greet](https://cloud.githubusercontent.com/assets/6137576/8413357/2bd7a850-1e90-11e5-8619-a96e940fe63e.PNG)
![greetins](https://cloud.githubusercontent.com/assets/6137576/8413468/f39c210e-1e90-11e5-8876-9b948a1729f2.PNG)
![goblingreet](https://cloud.githubusercontent.com/assets/6137576/8413739/0814a6a4-1e93-11e5-9b48-45aac37684b9.PNG)
![goblingreens](https://cloud.githubusercontent.com/assets/6137576/8413746/0e9bc124-1e93-11e5-8541-82d8d24a0a8e.PNG)
![greetingslad](https://cloud.githubusercontent.com/assets/6137576/8414170/5f1d97d2-1e96-11e5-8bf9-c619d1924eee.PNG)
![me book](https://cloud.githubusercontent.com/assets/6137576/8414208/9709fb54-1e96-11e5-8dc1-b978d080ceba.PNG)

**Comment by AsuraDev** [comment]
Adding a note to this. The reason we have this "Greetings" text here is because it's an actual packet that requires a text when creatures have 2 or more active quests(Person has a quest, or they start/finish a quest, etc)(This is when people see "Available quests" and "Current quests"). We figured out how it works properly, but we don't have the texts sniffed(no one does, from what we've seen).
