### ISSUE TITLE
Auto Shot, Throw, and Shoot fail to impact when facing the other way.

### ISSUE THREAD

**Issue by Crestfall** [Crestfall/JadefireTracker#2]
At the moment, if you use one of the above abilities, you can turn around while the projectile is in the air. When it lands and you're not facing the target, it has zero effect. 

Reproduction:
1 - Creature a rogue and find a creature
2 - Use the throw ability
3 - After the throw ability has gone off and the projectile is in air, turn around 180 degrees
4 - Throw projectile reaches target, nothing happens.

**Comment by AsuraDev** [comment]
Fixed. Will be on Alpha realm tomorrow.
