### ISSUE TITLE
[Pathing] Fel Rock (Teldrassil)

### ISSUE THREAD

**Issue by mirome** [Crestfall/JadefireTracker#20]
Mobs throughout several areas of Fel Rock (cave) have pathing issues. After being attacked they proceed to jump through the ceiling and no longer return to their original spot in the cave.

![fel rock 3](https://cloud.githubusercontent.com/assets/6696700/8031426/0b7a8206-0dc6-11e5-82f2-484ec977098f.jpg)

![fel rock 2](https://cloud.githubusercontent.com/assets/6696700/8031286/194a1456-0dc5-11e5-9205-f304080f91aa.jpg)

![fel rock](https://cloud.githubusercontent.com/assets/6696700/8031202/7e064ac8-0dc4-11e5-83d7-0095b5a66eb1.jpg)

![fel rock map](https://cloud.githubusercontent.com/assets/6696700/8031218/9b869530-0dc4-11e5-91aa-dc734b62aed6.jpg)

**Comment by AsuraDev** [comment]
Related to #8. Closing this as duplicate
