### ISSUE TITLE
[Pathing] Gnarlpine Warrior - Starbreeze Village (Teldrassil)

### ISSUE THREAD

**Issue by mirome** [Crestfall/JadefireTracker#21]
Unable to kill target.

![starbreeze village](https://cloud.githubusercontent.com/assets/6696700/8031635/fe082c20-0dc7-11e5-8ec7-ade0a94bd357.jpg)

![starbreeze village 2](https://cloud.githubusercontent.com/assets/6696700/8031636/fe0ac796-0dc7-11e5-8716-8e73adb1c4d3.jpg)

**Comment by AsuraDev** [comment]
Related to #8. Closing this as duplicate
