### ISSUE TITLE
[Quest - Auto Completes] Sathrah's Sacrifice (Darnassus)

### ISSUE THREAD

**Issue by mirome** [Crestfall/JadefireTracker#23]
Sathrah's Sacrifice (quest=2520) auto completes. Not possible to offer Sathrah's Sacrifice (item=8155) sacrifice to the fountain inside the temple.

![sathrah s sacrifice](https://cloud.githubusercontent.com/assets/6696700/8032994/bad3335e-0dd2-11e5-9ab9-d1616eac9ca9.jpg)

![sathrah s sacrifice 2](https://cloud.githubusercontent.com/assets/6696700/8032993/bad347c2-0dd2-11e5-8f42-de68cf84847d.jpg)

**Comment by AsuraDev** [comment]
Fixed. Spirit NPC and waypoints for it also implemented. Will be on Alpha realm tomorrow.
