### ISSUE TITLE
Delete guild masters

### ISSUE THREAD

**Issue by Daribon** [Crestfall/JadefireTracker#233]
It's currently possible to delete guild master characters, it shouldn't be possible.

It should probably use "CHAR_DELETE_FAILED = "Character deletion failed"; since "CHAR_DELETE_FAILED_GUILD_LEADER = "This character is a Guild Master and cannot be deleted until the rank is transferred to another character."; wasn't in the game in vanilla.

**Comment by AsuraDev** [comment]
Fixed.
