### ISSUE TITLE
[NPC] Kobold Laborer - floating waypoint

### ISSUE THREAD

**Issue by rzeg** [Crestfall/JadefireTracker#28]
Some Kobold Laborers have a tendency to go to a waypoint that causes them to float.
![wowscrnshot_060815_144545](https://cloud.githubusercontent.com/assets/175795/8035012/66d1cc28-0ded-11e5-8ef3-094455888b84.png)
![wowscrnshot_060815_144633](https://cloud.githubusercontent.com/assets/175795/8035013/66d21a16-0ded-11e5-9bc1-ff7776610291.png)

**Comment by AsuraDev** [comment]
Added a new way of handling random movement to avoid these type of issues in the future.
