### ISSUE TITLE
Player who kills creature always gets experience

### ISSUE THREAD

**Issue by Crestfall** [Crestfall/JadefireTracker#3]
Regardless of what is done with the creature, currently the one to kill it is the one who gets experience.

Reproduction:
1 - Create two characters
2 - Have Character A attack a creature until it has low life remaining(5% - 15%)
3 - Have Character B attack and finish off the creature
4 - Loot is assigned to Character A properly, but experience is assigned to Character B

**Comment by AsuraDev** [comment]
Fixed. Tagger(and their group, if they have one) will now get proper credit for experience.
