### ISSUE TITLE
[NPC/Quest] Chicken - Cluck!

### ISSUE THREAD

**Issue by rzeg** [Crestfall/JadefireTracker#30]
The quest Cluck! should only be available if you do /chicken at a chicken X amount of times, currently it's always available.

**Comment by AsuraDev** [comment]
Fixed. Chickens now require a certain amount + a randomized extra amount to change. Questgiver is only given for the player clucking. Egg is only lootable by the person who turns in the quest, and using /cheer when you have the feed + quest will automatically change the chicken. Will be on Alpha realm tomorrow.
