### ISSUE TITLE
Places that should dismount you

### ISSUE THREAD

**Issue by Daribon** [Crestfall/JadefireTracker#31]
Dark Portal should not allow players to be remain mounted while standing on it.
You shouldn't be able to mount in Booty Bay, anyone who played in pre WOTLK knows this.
You shouldn't be able to mount on the path leading from Blackrock Mountain to Burning Steppes.
The tunnel leading to the entrance of Razorfen Downs should dismount you.
The path in front of Stratholme's main entrance in Eastern Plaguelands should dismount you
Zeppelin Tower in Tirisfal Glades should dismount.

I believe most of the Night elf buildings should dismount you too, I've read about it on some forums.

Source: http://www.wowwiki.com/Patch_3.0.2_%28undocumented_changes%29 http://www.gamefaqs.com/boards/534914-world-of-warcraft/46527608 http://www.lurkerlounge.com/forums/thread-1479-page-2.html http://www.gamefaqs.com/boards/534914-world-of-warcraft/46002211 http://www.lurkerlounge.com/forums/thread-1479.html

**Comment by AsuraDev** [comment]
Fixed. Will be on server tomorrow.
