### ISSUE TITLE
Guild tabard designers broken

### ISSUE THREAD

**Issue by Daribon** [Crestfall/JadefireTracker#310]
All guild tabard designers in Azeroth are currently broken.
	
Ellaercia doesn't allow players to interact with her. She is supposed make the guild tabard design menu show up when you interact with her.

Edward Remington can be interact, but no guild design menu will show up and the chat log will spam the following:
![wow 2015-07-12 01-19-00](https://cloud.githubusercontent.com/assets/6137576/8635721/0b36fe04-2834-11e5-84f8-2b758e9fa6fa.png)

**Comment by AsuraDev** [comment]
Just editing this: Some are working properly, some are not. They're just missing gossip menus.
