### ISSUE TITLE
Skeleton despawn

### ISSUE THREAD

**Issue by Daribon** [Crestfall/JadefireTracker#322]
Skeletons does curently not despawn from what I've noticed. 
I'm pretty sure that corpses did despawn in vanilla. 

On retail patch 6.2 it takes about 4-5 hours for a corpse to despawn.

**Comment by AsuraDev** [comment]
They should despawn after 10 minutes or so... or I messed it up and it's aroudn 10000 minutes. Try and check again.

**Comment by AsuraDev** [comment]
Rejected. Tested with 10 minute timers (10 times total). Corpses always despawned. If need be, time can be altered, but they do despawn.
