### ISSUE TITLE
All inns around the world broken

### ISSUE THREAD

**Issue by Daribon** [Crestfall/JadefireTracker#327]
It appears all inns around the world are currently broken, when you step on the inn .wmo you get rested for about 1s and then it ends. I've tested several inns around Azeroth and they have all been broken so far. You are also able to get rested/insta logout during that 1s with a character of the opposite faction.
![raine](https://cloud.githubusercontent.com/assets/6137576/8909570/65f1b14a-3482-11e5-883d-da791e0fd87a.PNG)
![kathna](https://cloud.githubusercontent.com/assets/6137576/8909639/b92fa95c-3482-11e5-86a9-d581d26be7f4.PNG)
I've tried with many inns that don't look like this one. Tried with Lakeshire, Gadgetzan, Astranaar, Durotar, Splintertree, Crossroads, Kargath

Cities works just fine, so not sure what's up with all the inns.

**Comment by AsuraDev** [comment]
Fixed. New rested system has been built.
