### ISSUE TITLE
[Rogue] Expose Armor visual bug

### ISSUE THREAD

**Issue by Neretz** [Crestfall/JadefireTracker#360]
Currently Expose Armor not only procs the victim / onhit visual characterised as a shield effect on the enemy target, but also the Rogue aswell. It should only appear on the enemy target.

Reference (If needed): https://youtu.be/RjkqjTTdMYo?t=13m28s

**Comment by AsuraDev** [comment]
Yeah. Just saw it. That's a bit derp.
