### ISSUE TITLE
Applying poison breaks stealth

### ISSUE THREAD

**Issue by Daribon** [Crestfall/JadefireTracker#382]
Applying poison does currently break stealth.
You should be able to apply poisons while in stealth.

Patch 1.10.0 (2006-03-28): Applying Rogue poisons will no longer break Stealth. 
Source: http://web.archive.org/web/20101107215601/http://www.worldofwarcraft.com/patchnotes/patch1p10.html

According to old wowwiki page it should be possible to apply poison while in shadowmeld too since patch 1.10:
http://wowwiki.wikiaglobal.com/wiki/Rogue?oldid=309602

**Comment by AsuraDev** [comment]
Fixed due to a bad SPELL_ATTR_EX_PERSIST_STEALTH check
