### ISSUE TITLE
Temporary item enchants removal

### ISSUE THREAD

**Issue by Daribon** [Crestfall/JadefireTracker#384]
According to patch 1.10 patch notes temporary item buffs should get removed when zoning or logging out.

This may need some more research.

Patch 1.10
Temporary item buffs (e.g. poisons, sharpening stones and shaman weapon buffs) will persist through zoning or logging out. 
Source: http://eu.battle.net/wow/en/game/patch-notes/1-11-0

**Comment by AsuraDev** [comment]
Just a misreading, Closing this as we spoke about it on skype.
