### ISSUE TITLE
Vindication eaten by Grounding totem

### ISSUE THREAD

**Issue by Daribon** [Crestfall/JadefireTracker#389]
Grounding totem currently eats vindication debuff. It shouldn't be a possible.
![grounding](https://cloud.githubusercontent.com/assets/6137576/9281873/b3e94706-42c8-11e5-83c9-7822b65bbd63.PNG)

Patch 1.11.0:
Vindication: This effect will no longer be absorbed by Grounding Totem.
Source: http://eu.battle.net/wow/en/game/patch-notes/1-11-0

**Comment by AsuraDev** [comment]
Fixed this, along with some other spells that should not be eaten by Grounding.
