### ISSUE TITLE
Turning character causes movement glitch

### ISSUE THREAD

**Issue by Daribon** [Crestfall/JadefireTracker#39]
Sometimes when you move your character, it will make your character teleport a bit on other players screens.

You are not very likely to see it if player is keyboard turning, but if player is using mouse you are likely to see it sometimes.

**Comment by AsuraDev** [comment]
Cannot confirm. Only time I was able to see it on my side is when one of us modified our speeds using GM commands. Otherwise everyone ran perfectly fine to me.

**Comment by AsuraDev** [comment]
Last time we attempted to check this, it was due to GM related speed mods and latency, which it can be found in retail videos due to latency. Closing this as there is no "fix" required.
