### ISSUE TITLE
Viper sting active in non caster form

### ISSUE THREAD

**Issue by Daribon** [Crestfall/JadefireTracker#392]
Viper sting does currentlky drain mana from druids when they are not in caster form.
It should only drain mana when druid is in caster form.

Patch 1.4.0:
"Viper Sting - This spell can no longer be used on warrior and rogue targets. In addition, while it can be used on a druid target at any time it will only drain mana when the druid is in caster form."
Source: https://web.archive.org/web/20061110080240/http://www.worldofwarcraft.com/patchnotes/patch-05-04-19.html

**Comment by AsuraDev** [comment]
Fixed. Viper Sting is no longer castable when a character doesn't use mana, and if a druid changes form, mana is no longer taken
