### ISSUE TITLE
[Area] Cenarion Enclave - Underwater (Darnassus)

### ISSUE THREAD

**Issue by mirome** [Crestfall/JadefireTracker#51]
At the bottom of the Cenarion Enclave next to Erion Shadwshiper the area thinks you are underwater.

![cenarion enclave](https://cloud.githubusercontent.com/assets/6696700/8058857/4c3122d4-0eb4-11e5-89e2-6de4679366c7.jpg)

**Comment by AsuraDev** [comment]
Fixed. Will be on the test realm later today.
