### ISSUE TITLE
[Area/Quest] Blue Recluse - Mana Rift and Rift Spawns visible when not on mage quest

### ISSUE THREAD

**Issue by rzeg** [Crestfall/JadefireTracker#60]
The Rift spawns and the Mana rift should not be visible unless you are on the specific mage quest and follow it's instructions. More information here: http://www.wowhead.com/quest=1920/investigate-the-blue-recluse

![OMG](http://puu.sh/iituc/0d0787e2ad.jpg)

**Comment by AsuraDev** [comment]
Fixed. Will be on test realm later today.

**Comment by AsuraDev** [comment]
cancel that, after looking at it closer, need to make sure it works properly.
