### ISSUE TITLE
[Misc] Setting hearthstone confirmation disappears 2nd time

### ISSUE THREAD

**Issue by rzeg** [Crestfall/JadefireTracker#74]
When you try setting a hearthstone it will ask you if you want to set <Location> as your new home. You can either accept or cancel it. 

When you cancel it the first time the second time it won't ask for confirmation and will set the hearthstone immediately. 

Steps to reproduce:
1. Go to your favorite innkeeper and talk to him.
2. Press "Make this inn your home"
3. Press cancel.
4. Repeat steps 1 & 2.
5. Your hearthstone will be immediately be set without a confirmation box.

This could be a client quirk but I don't know how hearthstones are handled serverside

**Comment by AsuraDev** [comment]
Fixed. Rewrote how Hearthstones are handled due to the original Ascent way being ugly. Will be on the test realm with the update later today.
