### ISSUE TITLE
[Teleport] Teldrassil Portal to Auberdine (Rut'theran Village)

### ISSUE THREAD

**Issue by mirome** [Crestfall/JadefireTracker#81]
Portal that should not exist.

![teldrassil portal to auberdine](https://cloud.githubusercontent.com/assets/6696700/8066897/2455a6a8-0ee2-11e5-8432-5438c5f28f4f.jpg)

**Comment by Daribon** [comment]
It's placeholder since transports have been/are bugged atm.

**Comment by AsuraDev** [comment]
As Daribon said, placeholder until the transport system has been rewritten.
