### ISSUE TITLE
Thelsamar random movement

### ISSUE THREAD

**Issue by Daribon** [Crestfall/JadefireTracker#82]
-- Mountaineer Dalk 11850 should have random movement
-- Mountaineer Uthan 11783 should have random movement
-- Mountaineer Bludd 11782 should have random movement
-- Mountaineer Fazgrad 11847 should have random movement
-- Mountaineer Swarth 11582 should have random movement
-- Mountaineer Harn 11846 should have random movement
-- Mountaineer Roghan 11779 should have random movement
-- Mountainer Wuar 11845 should have random movement

There are some other NPCs in Thelsamar that might need random movement, but I will have to research those more.

**Comment by GorbulasCrestfall** [comment]
Fixed the above mentioned NPCs. Leaving this open for future possible additions.
