### ISSUE TITLE
[Mail] Able to mail self

### ISSUE THREAD

**Issue by rzeg** [Crestfall/JadefireTracker#83]
I don't think you are supposed to be able to mail yourself

![d](http://puu.sh/iiCL9/49b372f9cc.jpg)

**Comment by Daribon** [comment]
On retail if you attempt to send a mail to yourself it will tell you "You can't send mail to yourself"

**Comment by AsuraDev** [comment]
Fixed. Was a bad check. Will be on the test realm with the update later today.
