### ISSUE TITLE
[Quest] Deeprun Rat Roundup

### ISSUE THREAD

**Issue by rzeg** [Crestfall/JadefireTracker#99]
You are able to use the quest item on the rats and they turn to minions but they don't follow you around and don't give quest credit.

![d](http://puu.sh/ijFeI/0c8e780adc.jpg)
The rats should follow you and give you credit when you use the flute provided. See the following video for reference: https://www.youtube.com/watch?v=U11BArF432g

**Comment by AsuraDev** [comment]
Shoulda told me on IRC. I forgot to attach the new AI to it. Will be updated on test server tomorrow!

**Comment by AsuraDev** [comment]
Re-opening this because due to new AI, half their script isn't needed. Just going to rewrite it, so leaving it "open" until that's done.
